/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) MPC_simplified_qpoases_prep_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

#define casadi_to_int(x) ((casadi_int) x)

#ifndef casadi_inf
  #define casadi_inf INFINITY
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s5[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};

/* form_Hk:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(Hk[3x3]) */
static int casadi_f1(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
    a0=arg[3]? arg[3][0] : 0;
    a0=(a0+a0);
    if (res[0]!=0) res[0][0]=a0;
    a0=0.;
    if (res[0]!=0) res[0][1]=a0;
    if (res[0]!=0) res[0][2]=a0;
    if (res[0]!=0) res[0][3]=a0;
    a1=arg[4]? arg[4][0] : 0;
    a1=(a1+a1);
    if (res[0]!=0) res[0][4]=a1;
    if (res[0]!=0) res[0][5]=a0;
    if (res[0]!=0) res[0][6]=a0;
    if (res[0]!=0) res[0][7]=a0;
    a0=arg[5]? arg[5][0] : 0;
    a0=(a0+a0);
    if (res[0]!=0) res[0][8]=a0;
    return 0;
}

/* MPC_simplified_form_H:(i0,i1[3],i2[2],i3,i4,i5,i6,i7)->(o0[3x3]) */
static int casadi_f0(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    switch (arg[0] ? casadi_to_int(*arg[0]) : 0) {
        case 0:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 1:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 2:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 3:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 4:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 5:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 6:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 7:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 8:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 9:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 10:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 11:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 12:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 13:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 14:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 15:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 16:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 17:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 18:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 19:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 20:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 21:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 22:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 23:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 24:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 25:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 26:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 27:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 28:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 29:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 30:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 31:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 32:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 33:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 34:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 35:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 36:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 37:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 38:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 39:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 40:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 41:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 42:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 43:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 44:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 45:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 46:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 47:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 48:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        case 49:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
        default:
        if (casadi_f1(arg+1, res, iw, w, 0)) return 1;
        break;
    }
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_H(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_H_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_H_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_H_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_H_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_H_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_H_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_H_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_H_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_H_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_H_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_H_name_in(casadi_int i) {
    switch (i) {
        case 0: return "i0";
        case 1: return "i1";
        case 2: return "i2";
        case 3: return "i3";
        case 4: return "i4";
        case 5: return "i5";
        case 6: return "i6";
        case 7: return "i7";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_H_name_out(casadi_int i) {
    switch (i) {
        case 0: return "o0";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_H_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s1;
        case 2: return casadi_s2;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        case 7: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_H_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_H_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 15;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 2;
    return 0;
}

/* form_gk:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(gk[3]) */
static int casadi_f3(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
    a0=arg[0]? arg[0][0] : 0;
    a1=arg[3]? arg[3][0] : 0;
    a2=(a0*a1);
    a3=(a1*a0);
    a2=(a2+a3);
    a3=5.0000000000000000e-01;
    a4=(a3*a0);
    a1=(a1+a1);
    a4=(a4*a1);
    a1=(a1*a0);
    a1=(a3*a1);
    a4=(a4+a1);
    a2=(a2-a4);
    if (res[0]!=0) res[0][0]=a2;
    a2=arg[0]? arg[0][1] : 0;
    a4=arg[4]? arg[4][0] : 0;
    a1=(a2*a4);
    a0=(a4*a2);
    a1=(a1+a0);
    a0=(a3*a2);
    a4=(a4+a4);
    a0=(a0*a4);
    a4=(a4*a2);
    a4=(a3*a4);
    a0=(a0+a4);
    a1=(a1-a0);
    if (res[0]!=0) res[0][1]=a1;
    a1=arg[0]? arg[0][2] : 0;
    a0=arg[5]? arg[5][0] : 0;
    a4=(a1*a0);
    a2=(a0*a1);
    a4=(a4+a2);
    a2=(a3*a1);
    a0=(a0+a0);
    a2=(a2*a0);
    a0=(a0*a1);
    a3=(a3*a0);
    a2=(a2+a3);
    a4=(a4-a2);
    if (res[0]!=0) res[0][2]=a4;
    return 0;
}

/* MPC_simplified_form_g:(i0,i1[3],i2[2],i3,i4,i5,i6,i7)->(o0[3]) */
static int casadi_f2(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    switch (arg[0] ? casadi_to_int(*arg[0]) : 0) {
        case 0:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 1:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 2:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 3:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 4:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 5:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 6:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 7:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 8:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 9:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 10:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 11:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 12:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 13:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 14:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 15:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 16:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 17:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 18:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 19:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 20:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 21:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 22:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 23:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 24:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 25:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 26:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 27:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 28:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 29:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 30:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 31:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 32:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 33:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 34:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 35:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 36:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 37:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 38:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 39:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 40:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 41:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 42:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 43:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 44:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 45:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 46:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 47:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 48:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        case 49:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
        default:
        if (casadi_f3(arg+1, res, iw, w, 0)) return 1;
        break;
    }
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_g(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_g_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_g_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_g_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_g_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_g_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_g_name_in(casadi_int i) {
    switch (i) {
        case 0: return "i0";
        case 1: return "i1";
        case 2: return "i2";
        case 3: return "i3";
        case 4: return "i4";
        case 5: return "i5";
        case 6: return "i6";
        case 7: return "i7";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_g_name_out(casadi_int i) {
    switch (i) {
        case 0: return "o0";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_g_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s1;
        case 2: return casadi_s2;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        case 7: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_g_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 15;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 5;
    return 0;
}

/* MPC_simplified_form_HN:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(HN[2x2]) */
static int casadi_f4(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
    a0=arg[3]? arg[3][0] : 0;
    a0=(a0+a0);
    if (res[0]!=0) res[0][0]=a0;
    a0=0.;
    if (res[0]!=0) res[0][1]=a0;
    if (res[0]!=0) res[0][2]=a0;
    a0=arg[4]? arg[4][0] : 0;
    a0=(a0+a0);
    if (res[0]!=0) res[0][3]=a0;
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_HN(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_HN_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_HN_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_HN_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_HN_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_HN_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_HN_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_HN_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_HN_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_HN_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_HN_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_HN_name_in(casadi_int i) {
    switch (i) {
        case 0: return "z_op";
        case 1: return "x0";
        case 2: return "pd";
        case 3: return "Q11";
        case 4: return "Q22";
        case 5: return "R";
        case 6: return "umax";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_HN_name_out(casadi_int i) {
    switch (i) {
        case 0: return "HN";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_HN_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s2;
        case 2: return casadi_s0;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_HN_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_HN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 7;
    if (sz_res) *sz_res = 1;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* MPC_simplified_form_gN:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(gN[2]) */
static int casadi_f5(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
    a0=arg[0]? arg[0][0] : 0;
    a1=arg[3]? arg[3][0] : 0;
    a2=(a0*a1);
    a3=(a1*a0);
    a2=(a2+a3);
    a3=5.0000000000000000e-01;
    a1=(a1+a1);
    a4=(a3*a1);
    a4=(a0*a4);
    a0=(a3*a0);
    a0=(a0*a1);
    a4=(a4+a0);
    a2=(a2-a4);
    if (res[0]!=0) res[0][0]=a2;
    a2=arg[0]? arg[0][1] : 0;
    a4=arg[4]? arg[4][0] : 0;
    a0=(a2*a4);
    a1=(a4*a2);
    a0=(a0+a1);
    a4=(a4+a4);
    a1=(a3*a4);
    a1=(a2*a1);
    a3=(a3*a2);
    a3=(a3*a4);
    a1=(a1+a3);
    a0=(a0-a1);
    if (res[0]!=0) res[0][1]=a0;
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_gN(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_gN_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_gN_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_gN_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_gN_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_gN_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_gN_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_gN_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_gN_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_gN_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_gN_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_gN_name_in(casadi_int i) {
    switch (i) {
        case 0: return "z_op";
        case 1: return "x0";
        case 2: return "pd";
        case 3: return "Q11";
        case 4: return "Q22";
        case 5: return "R";
        case 6: return "umax";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_gN_name_out(casadi_int i) {
    switch (i) {
        case 0: return "gN";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_gN_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s2;
        case 2: return casadi_s0;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_gN_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s2;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_gN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 7;
    if (sz_res) *sz_res = 1;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* form_dynamics:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(AB[3x2],b[2]) */
static int casadi_f7(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3, a4, a5, a6, a7, a8, a9;
    a0=9.9481724303385421e-01;
    if (res[0]!=0) res[0][0]=a0;
    a1=1.8928578294270835e-02;
    if (res[0]!=0) res[0][1]=a1;
    a2=2.4105846354166669e-04;
    if (res[0]!=0) res[0][2]=a2;
    a3=-5.0870554165852866e-01;
    if (res[0]!=0) res[0][3]=a3;
    a4=8.9307613470214842e-01;
    if (res[0]!=0) res[0][4]=a4;
    a5=2.3660722867838546e-02;
    if (res[0]!=0) res[0][5]=a5;
    a6=arg[0]? arg[0][0] : 0;
    a7=3.3333333333333335e-03;
    a8=arg[0]? arg[0][1] : 0;
    a9=2.;
    a10=1.0000000000000000e-02;
    a11=-2.6874999999999996e+01;
    a12=(a11*a6);
    a13=5.3750000000000000e+00;
    a14=(a13*a8);
    a12=(a12-a14);
    a14=1.2500000000000000e+00;
    a15=arg[2]? arg[2][0] : 0;
    a16=arg[0]? arg[0][2] : 0;
    a15=(a15-a16);
    a14=(a14*a15);
    a12=(a12-a14);
    a15=(a10*a12);
    a15=(a8+a15);
    a17=(a9*a15);
    a17=(a8+a17);
    a18=(a10*a8);
    a18=(a6+a18);
    a18=(a11*a18);
    a19=(a13*a15);
    a18=(a18-a19);
    a18=(a18-a14);
    a19=(a10*a18);
    a19=(a8+a19);
    a20=(a9*a19);
    a17=(a17+a20);
    a20=2.0000000000000000e-02;
    a10=(a10*a15);
    a10=(a6+a10);
    a10=(a11*a10);
    a15=(a13*a19);
    a10=(a10-a15);
    a10=(a10-a14);
    a15=(a20*a10);
    a15=(a8+a15);
    a17=(a17+a15);
    a17=(a7*a17);
    a17=(a6+a17);
    a0=(a0*a6);
    a1=(a1*a8);
    a0=(a0+a1);
    a2=(a2*a16);
    a0=(a0+a2);
    a17=(a17-a0);
    if (res[1]!=0) res[1][0]=a17;
    a18=(a9*a18);
    a12=(a12+a18);
    a9=(a9*a10);
    a12=(a12+a9);
    a20=(a20*a19);
    a20=(a6+a20);
    a11=(a11*a20);
    a13=(a13*a15);
    a11=(a11-a13);
    a11=(a11-a14);
    a12=(a12+a11);
    a7=(a7*a12);
    a7=(a8+a7);
    a3=(a3*a6);
    a4=(a4*a8);
    a3=(a3+a4);
    a5=(a5*a16);
    a3=(a3+a5);
    a7=(a7-a3);
    if (res[1]!=0) res[1][1]=a7;
    return 0;
}

/* MPC_simplified_form_dynamics:(i0,i1[3],i2[2],i3,i4,i5,i6,i7)->(o0[3x2],o1[2]) */
static int casadi_f6(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    switch (arg[0] ? casadi_to_int(*arg[0]) : 0) {
        case 0:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 1:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 2:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 3:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 4:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 5:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 6:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 7:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 8:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 9:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 10:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 11:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 12:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 13:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 14:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 15:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 16:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 17:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 18:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 19:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 20:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 21:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 22:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 23:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 24:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 25:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 26:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 27:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 28:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 29:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 30:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 31:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 32:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 33:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 34:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 35:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 36:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 37:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 38:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 39:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 40:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 41:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 42:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 43:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 44:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 45:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 46:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 47:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 48:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        case 49:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
        default:
        if (casadi_f7(arg+1, res, iw, w, 0)) return 1;
        break;
    }
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_dynamics(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_dynamics_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_dynamics_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_dynamics_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_dynamics_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_dynamics_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_dynamics_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_dynamics_name_in(casadi_int i) {
    switch (i) {
        case 0: return "i0";
        case 1: return "i1";
        case 2: return "i2";
        case 3: return "i3";
        case 4: return "i4";
        case 5: return "i5";
        case 6: return "i6";
        case 7: return "i7";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_dynamics_name_out(casadi_int i) {
    switch (i) {
        case 0: return "o0";
        case 1: return "o1";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_dynamics_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s1;
        case 2: return casadi_s2;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        case 7: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_dynamics_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s5;
        case 1: return casadi_s2;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 15;
    if (sz_res) *sz_res = 4;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 21;
    return 0;
}

/* form_bounds0:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(zlow0[3],zupp0[3]) */
static int casadi_f9(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
    a0=arg[1]? arg[1][0] : 0;
    if (res[0]!=0) res[0][0]=a0;
    a1=arg[1]? arg[1][1] : 0;
    if (res[0]!=0) res[0][1]=a1;
    a2=arg[6]? arg[6][0] : 0;
    a3=(-a2);
    if (res[0]!=0) res[0][2]=a3;
    if (res[1]!=0) res[1][0]=a0;
    if (res[1]!=0) res[1][1]=a1;
    if (res[1]!=0) res[1][2]=a2;
    return 0;
}

/* form_boundsk:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(zlowk[3],zuppk[3]) */
static int casadi_f10(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
    a0=-casadi_inf;
    if (res[0]!=0) res[0][0]=a0;
    if (res[0]!=0) res[0][1]=a0;
    a0=arg[6]? arg[6][0] : 0;
    a1=(-a0);
    if (res[0]!=0) res[0][2]=a1;
    a1=casadi_inf;
    if (res[1]!=0) res[1][0]=a1;
    if (res[1]!=0) res[1][1]=a1;
    if (res[1]!=0) res[1][2]=a0;
    return 0;
}

/* MPC_simplified_form_bounds:(i0,i1[3],i2[2],i3,i4,i5,i6,i7)->(o0[3],o1[3]) */
static int casadi_f8(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    switch (arg[0] ? casadi_to_int(*arg[0]) : 0) {
        case 0:
        if (casadi_f9(arg+1, res, iw, w, 0)) return 1;
        break;
        case 1:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 2:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 3:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 4:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 5:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 6:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 7:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 8:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 9:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 10:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 11:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 12:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 13:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 14:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 15:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 16:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 17:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 18:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 19:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 20:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 21:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 22:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 23:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 24:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 25:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 26:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 27:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 28:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 29:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 30:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 31:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 32:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 33:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 34:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 35:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 36:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 37:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 38:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 39:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 40:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 41:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 42:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 43:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 44:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 45:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 46:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 47:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 48:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        case 49:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
        default:
        if (casadi_f10(arg+1, res, iw, w, 0)) return 1;
        break;
    }
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_bounds(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_bounds_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_bounds_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_bounds_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_bounds_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_bounds_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_bounds_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_bounds_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_bounds_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_bounds_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_bounds_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_bounds_name_in(casadi_int i) {
    switch (i) {
        case 0: return "i0";
        case 1: return "i1";
        case 2: return "i2";
        case 3: return "i3";
        case 4: return "i4";
        case 5: return "i5";
        case 6: return "i6";
        case 7: return "i7";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_bounds_name_out(casadi_int i) {
    switch (i) {
        case 0: return "o0";
        case 1: return "o1";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_bounds_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s1;
        case 2: return casadi_s2;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        case 7: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_bounds_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s1;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_bounds_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 15;
    if (sz_res) *sz_res = 4;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 4;
    return 0;
}

/* MPC_simplified_form_boundsN:(z_op[3],x0[2],pd,Q11,Q22,R,umax)->(zlowN[2],zuppN[2]) */
static int casadi_f11(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
    a0=-casadi_inf;
    if (res[0]!=0) res[0][0]=a0;
    if (res[0]!=0) res[0][1]=a0;
    a0=casadi_inf;
    if (res[1]!=0) res[1][0]=a0;
    if (res[1]!=0) res[1][1]=a0;
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_boundsN(casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_boundsN_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_boundsN_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_boundsN_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_boundsN_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_boundsN_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_boundsN_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_simplified_form_boundsN_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_boundsN_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int MPC_simplified_form_boundsN_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real MPC_simplified_form_boundsN_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_boundsN_name_in(casadi_int i) {
    switch (i) {
        case 0: return "z_op";
        case 1: return "x0";
        case 2: return "pd";
        case 3: return "Q11";
        case 4: return "Q22";
        case 5: return "R";
        case 6: return "umax";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* MPC_simplified_form_boundsN_name_out(casadi_int i) {
    switch (i) {
        case 0: return "zlowN";
        case 1: return "zuppN";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_boundsN_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s2;
        case 2: return casadi_s0;
        case 3: return casadi_s0;
        case 4: return casadi_s0;
        case 5: return casadi_s0;
        case 6: return casadi_s0;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_simplified_form_boundsN_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s2;
        case 1: return casadi_s2;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int MPC_simplified_form_boundsN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 7;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
